// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/15/2025, 5:32:08 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/thier/projects/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/thier/projects/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/thier/projects/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/thier/projects/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/thier/projects/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/thier/projects/plugins/**/*.{js,ts,mjs}","/home/thier/projects/composables/**/*.{js,ts,mjs}","/home/thier/projects/utils/**/*.{js,ts,mjs}","/home/thier/projects/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/thier/projects/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/thier/projects/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;